### ISSUE TITLE
$include in InitialWorkDirRequirement flagged incorrectly as error

### ISSUE THREAD

**Issue by pvanheus** [rabix/benten#100]
Example CWL tool:

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

requirements:
  InitialWorkDirRequirement:
    listing:
      - entryname: bug1.txt
        entry:
          $include: "bug1.txt"

inputs:
  one:
    type: string

stdout: bug1.out

outputs:
  output:
    type: stdout

baseCommand: [ cat, bug1.txt ]
```

where `bug1.txt` is:

```
some text
```

benten 2020.06.03.1 flags the `$include: "bug1.txt"` as an error: "Got type (unknown). Expecting one of ['string', 'Expression']". The code is, however, valid CWL.
