### ISSUE TITLE
Validation errors in list show wrong line no

### ISSUE THREAD

**Issue by kaushik-work** [rabix/benten#37]
e.g.

```
requirements:
  - class: ScatterFeatureRequirement
  - class: InlineJavascriptRequirement
  - pass: MultipleInputFeatureRequirement
```

will flag the error on the first item of the list, rather than the last
